// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team4546.robot2.subsystems;

import org.usfirst.frc.team4546.robot2.RobotMap;
import org.usfirst.frc.team4546.robot2.commands.*;
import org.usfirst.frc.team4546.robot2.Robot;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class Drivetrain extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Talon frontLeft = RobotMap.drivetrainfrontLeft;
    Talon rearLeft = RobotMap.drivetrainrearLeft;
    Talon frontRight = RobotMap.drivetrainfrontRight;
    Talon rearRight = RobotMap.drivetrainrearRight;
    RobotDrive chassis = RobotMap.drivetrainChassis;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new Drive());
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }

    //Method for driving with mecanum
	public void mecanumDrive(double x, double y, double z, double speed) {
		chassis.mecanumDrive_Cartesian(x*speed, y*speed, z*speed, 0);
		
	}
	
	//Method for stopping the robot
	public void driveStop()	{
		
		chassis.drive(0,0);
	}
	
	//Make this return false to disable autonomous

}

